// Mocks generated by Mockito from annotations
// in consultar_imei/test/domain/consult_imei_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:consultar_imei/domain/entities/imei_entity.dart' as _i2;
import 'package:consultar_imei/domain/repositories/imei_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImeiEntity_0 extends _i1.SmartFake implements _i2.ImeiEntity {
  _FakeImeiEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ImeiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockImeiRepository extends _i1.Mock implements _i3.ImeiRepository {
  MockImeiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ImeiEntity> consultarImei(String? imei) => (super.noSuchMethod(
    Invocation.method(#consultarImei, [imei]),
    returnValue: _i4.Future<_i2.ImeiEntity>.value(
      _FakeImeiEntity_0(this, Invocation.method(#consultarImei, [imei])),
    ),
  ) as _i4.Future<_i2.ImeiEntity>);
}
